### ISSUE TITLE
https://flask-fs.readthedocs.io/ -- not found!

### ISSUE THREAD

**Issue by pahaz** [noirbizarre/flask-fs#3]

**Comment by pahaz** [comment]
![image](https://cloud.githubusercontent.com/assets/1394025/16723724/2900b124-4768-11e6-90e8-bc17f0cce25b.png)

**Comment by noirbizarre** [comment]
Sorry, for the late response
As it wasn't released only latest version was aavailable. Now stable version is available too and the link is working.
